#
# MPFS Embedded Software
#
# Copyright 2019-2021 Microchip FPGA Embedded Systems Solutions.
#
# SPDX-License-Identifier: MIT
#
# Middleware Software

include src/middleware/FreeRTOS/Makefile
include src/middleware/RTThread/Makefile
include src/middleware/misc/Makefile
include src/middleware/rpmsg/Makefile

ifdef REMOTEPROC
include src/middleware/remoteproc/Makefile
endif